// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/product.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	Store         string                 `protobuf:"bytes,7,opt,name=store,proto3" json:"store,omitempty"`
	PricePerUnit  float64                `protobuf:"fixed64,8,opt,name=pricePerUnit,proto3" json:"pricePerUnit,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,9,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_internal_proto_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_internal_proto_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Product) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Product) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *Product) GetPricePerUnit() float64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

func (x *Product) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_internal_proto_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ProductList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductList) Reset() {
	*x = ProductList{}
	mi := &file_internal_proto_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductList) ProtoMessage() {}

func (x *ProductList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductList.ProtoReflect.Descriptor instead.
func (*ProductList) Descriptor() ([]byte, []int) {
	return file_internal_proto_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductList) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type ProductIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductIdRequest) Reset() {
	*x = ProductIdRequest{}
	mi := &file_internal_proto_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductIdRequest) ProtoMessage() {}

func (x *ProductIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductIdRequest.ProtoReflect.Descriptor instead.
func (*ProductIdRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	Store         string                 `protobuf:"bytes,6,opt,name=store,proto3" json:"store,omitempty"`
	PricePerUnit  float64                `protobuf:"fixed64,7,opt,name=pricePerUnit,proto3" json:"pricePerUnit,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,8,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductRequest) Reset() {
	*x = AddProductRequest{}
	mi := &file_internal_proto_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductRequest) ProtoMessage() {}

func (x *AddProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductRequest.ProtoReflect.Descriptor instead.
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_product_proto_rawDescGZIP(), []int{4}
}

func (x *AddProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddProductRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddProductRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *AddProductRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *AddProductRequest) GetPricePerUnit() float64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

func (x *AddProductRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type AddProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*AddProductRequest   `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductsRequest) Reset() {
	*x = AddProductsRequest{}
	mi := &file_internal_proto_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsRequest) ProtoMessage() {}

func (x *AddProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsRequest.ProtoReflect.Descriptor instead.
func (*AddProductsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_product_proto_rawDescGZIP(), []int{5}
}

func (x *AddProductsRequest) GetProducts() []*AddProductRequest {
	if x != nil {
		return x.Products
	}
	return nil
}

type ProductsIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsIdsRequest) Reset() {
	*x = ProductsIdsRequest{}
	mi := &file_internal_proto_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsIdsRequest) ProtoMessage() {}

func (x *ProductsIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsIdsRequest.ProtoReflect.Descriptor instead.
func (*ProductsIdsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_product_proto_rawDescGZIP(), []int{6}
}

func (x *ProductsIdsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_internal_proto_product_proto protoreflect.FileDescriptor

const file_internal_proto_product_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/product.proto\x12\aproduct\"\xeb\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12\x14\n" +
	"\x05store\x18\a \x01(\tR\x05store\x12\"\n" +
	"\fpricePerUnit\x18\b \x01(\x01R\fpricePerUnit\x12\x1a\n" +
	"\bimageUrl\x18\t \x01(\tR\bimageUrl\"=\n" +
	"\x0fProductResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\";\n" +
	"\vProductList\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\"\"\n" +
	"\x10ProductIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe5\x01\n" +
	"\x11AddProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12\x14\n" +
	"\x05store\x18\x06 \x01(\tR\x05store\x12\"\n" +
	"\fpricePerUnit\x18\a \x01(\x01R\fpricePerUnit\x12\x1a\n" +
	"\bimageUrl\x18\b \x01(\tR\bimageUrl\"L\n" +
	"\x12AddProductsRequest\x126\n" +
	"\bproducts\x18\x01 \x03(\v2\x1a.product.AddProductRequestR\bproducts\"&\n" +
	"\x12ProductsIdsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids2\xa4\x02\n" +
	"\x0eProductService\x12E\n" +
	"\x0eGetProductById\x12\x19.product.ProductIdRequest\x1a\x18.product.ProductResponse\x12B\n" +
	"\n" +
	"AddProduct\x12\x1a.product.AddProductRequest\x1a\x18.product.ProductResponse\x12E\n" +
	"\x10GetProductsByIds\x12\x1b.product.ProductsIdsRequest\x1a\x14.product.ProductList\x12@\n" +
	"\vAddProducts\x12\x1b.product.AddProductsRequest\x1a\x14.product.ProductListB\tZ\a./protob\x06proto3"

var (
	file_internal_proto_product_proto_rawDescOnce sync.Once
	file_internal_proto_product_proto_rawDescData []byte
)

func file_internal_proto_product_proto_rawDescGZIP() []byte {
	file_internal_proto_product_proto_rawDescOnce.Do(func() {
		file_internal_proto_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_product_proto_rawDesc), len(file_internal_proto_product_proto_rawDesc)))
	})
	return file_internal_proto_product_proto_rawDescData
}

var file_internal_proto_product_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_proto_product_proto_goTypes = []any{
	(*Product)(nil),            // 0: product.Product
	(*ProductResponse)(nil),    // 1: product.ProductResponse
	(*ProductList)(nil),        // 2: product.ProductList
	(*ProductIdRequest)(nil),   // 3: product.ProductIdRequest
	(*AddProductRequest)(nil),  // 4: product.AddProductRequest
	(*AddProductsRequest)(nil), // 5: product.AddProductsRequest
	(*ProductsIdsRequest)(nil), // 6: product.ProductsIdsRequest
}
var file_internal_proto_product_proto_depIdxs = []int32{
	0, // 0: product.ProductResponse.product:type_name -> product.Product
	0, // 1: product.ProductList.products:type_name -> product.Product
	4, // 2: product.AddProductsRequest.products:type_name -> product.AddProductRequest
	3, // 3: product.ProductService.GetProductById:input_type -> product.ProductIdRequest
	4, // 4: product.ProductService.AddProduct:input_type -> product.AddProductRequest
	6, // 5: product.ProductService.GetProductsByIds:input_type -> product.ProductsIdsRequest
	5, // 6: product.ProductService.AddProducts:input_type -> product.AddProductsRequest
	1, // 7: product.ProductService.GetProductById:output_type -> product.ProductResponse
	1, // 8: product.ProductService.AddProduct:output_type -> product.ProductResponse
	2, // 9: product.ProductService.GetProductsByIds:output_type -> product.ProductList
	2, // 10: product.ProductService.AddProducts:output_type -> product.ProductList
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_product_proto_init() }
func file_internal_proto_product_proto_init() {
	if File_internal_proto_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_product_proto_rawDesc), len(file_internal_proto_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_product_proto_goTypes,
		DependencyIndexes: file_internal_proto_product_proto_depIdxs,
		MessageInfos:      file_internal_proto_product_proto_msgTypes,
	}.Build()
	File_internal_proto_product_proto = out.File
	file_internal_proto_product_proto_goTypes = nil
	file_internal_proto_product_proto_depIdxs = nil
}
