apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: auditservice
  name: auditservice
spec:
  ports:
    - name: "8088"
      port: 8088
      targetPort: 8080
  selector:
    io.kompose.service: auditservice
