apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: auditservice
  name: auditservice
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: auditservice
      name: latest
      referencePolicy:
        type: ""
