apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kong
  name: kong
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "8001"
      port: 8001
      targetPort: 8001
    - name: "8002"
      port: 8002
      targetPort: 8002
    - name: "8443"
      port: 8443
      targetPort: 8443
  selector:
    io.kompose.service: kong
