apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: kong-migrations
  name: kong-migrations
spec:
  containers:
    - args:
        - kong
        - migrations
        - bootstrap
      env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_HOST
          value: kong-db
        - name: KONG_PG_PASSWORD
          value: kong
        - name: KONG_PG_USER
          value: kong
      image: kong:3.6
      name: kong-migrations
  restartPolicy: OnFailure
