apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mfe-search
  name: mfe-search
spec:
  ports:
    - name: "3002"
      port: 3002
      targetPort: 80
  selector:
    io.kompose.service: mfe-search
