apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: mfe-search
  name: mfe-search
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: mfe-search
      name: latest
      referencePolicy:
        type: ""
