apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mfe-user
  name: mfe-user
spec:
  ports:
    - name: "3003"
      port: 3003
      targetPort: 80
  selector:
    io.kompose.service: mfe-user
