apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: mongo
      name: latest
      referencePolicy:
        type: ""
