apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: productservice
  name: productservice
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: productservice
      name: latest
      referencePolicy:
        type: ""
