apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: searchservice
  name: searchservice
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 8000
  selector:
    io.kompose.service: searchservice
