apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: searchservice
  name: searchservice
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: searchservice
      name: latest
      referencePolicy:
        type: ""
