apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: shell
  name: shell
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: shell
      name: latest
      referencePolicy:
        type: ""
