apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: tyk-gateway
  name: tyk-gateway
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 8080
  selector:
    io.kompose.service: tyk-gateway
