apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: userservice
  name: userservice
spec:
  ports:
    - name: "7207"
      port: 7207
      targetPort: 8080
  selector:
    io.kompose.service: userservice
