apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: userservice
  name: userservice
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: userservice
      name: latest
      referencePolicy:
        type: ""
