name: Search MFE CI

on:
  push:
    branches:
      - main
    paths:
      - 'micro-frontends/mfe-search/**'
  pull_request:
    branches:
      - main
    paths:
      - 'micro-frontends/mfe-search/**'
  workflow_dispatch:

jobs:
  dockerize-and-push-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/smartshopper-mfe_search:dev micro-frontends/mfe-search
          docker tag ${{ secrets.DOCKER_USERNAME }}/smartshopper-mfe_search:dev ${{ secrets.DOCKER_USERNAME }}/smartshopper-mfe_search:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/smartshopper-mfe_search:dev
          docker push ${{ secrets.DOCKER_USERNAME }}/smartshopper-mfe_search:${{ github.sha }}