name: Product Service CI

on:
  push:
    branches:
      - main
    paths:
      - 'ProductService/**'
  pull_request:
    branches:
      - main
    paths:
      - 'ProductService/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24  

    - name: Install dependencies
      run: |
        cd ProductService
        go mod tidy 

    - name: Run Tests
      run: |
        cd ProductService
        go test ./tests/... -v