name: Product Service CI

on:
  push:
    branches:
      - main
    paths:
      - 'ProductService/**'
  pull_request:
    branches:
      - main
    paths:
      - 'ProductService/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24  

    - name: Install dependencies
      run: |
        cd ProductService
        go mod tidy 

    - name: Run Tests
      run: |
        cd ProductService
        go test ./tests/... -v

  dockerize-and-push-dev:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/smartshopper-product_service:dev ProductService
          docker tag ${{ secrets.DOCKER_USERNAME }}/smartshopper-product_service:dev ${{ secrets.DOCKER_USERNAME }}/smartshopper-product_service:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/smartshopper-product_service:dev
          docker push ${{ secrets.DOCKER_USERNAME }}/smartshopper-product_service:${{ github.sha }}