name: Search Service CI

on:
  push:
    branches:
      - main
    paths:
      - 'SearchService/**'
  pull_request:
    branches:
      - main
    paths:
      - 'SearchService/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('SearchService/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r SearchService/requirements.txt

    - name: Run tests
      run: |
        cd SearchService
        pytest tests

  dockerize-and-push-dev:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/smartshopper-search_service:dev SearchService
          docker tag ${{ secrets.DOCKER_USERNAME }}/smartshopper-search_service:dev ${{ secrets.DOCKER_USERNAME }}/smartshopper-search_service:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/smartshopper-search_service:dev
          docker push ${{ secrets.DOCKER_USERNAME }}/smartshopper-search_service:${{ github.sha }}